### ISSUE TITLE
 minimatch is not a function

### ISSUE THREAD

**Issue by bbshih** [figma/code-connect#61]
Running `yarn figma connect publish` I see this error:

```No config file found in /Users/a/dev/my_code, proceeding with default options
/Users/username/dev/my_code/Button.figma.tsx
/Users/username/dev/my_code/node_modules/@figma/code-connect/dist/storybook/convert.js:24
    const storyFiles = files.filter((file) => (0, minimatch_1.minimatch)(file, storiesGlob, { matchBase: true }));
                                                                        ^

TypeError: (0 , minimatch_1.minimatch) is not a function
    at /Users/username/dev/my_code/node_modules/@figma/code-connect/dist/storybook/convert.js:24:73
    at Array.filter (<anonymous>)
    at convertStorybookFiles (/Users/username/dev/my_code/node_modules/@figma/code-connect/dist/storybook/convert.js:24:30)
    at Command.handlePublish (/Users/username/dev/my_code/node_modules/@figma/code-connect/dist/commands/connect.js:99:83)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I've tried with `npx` and deleting node_modules and reinstalling code connect but still run into this error. Any ideas of how to fix this?

**Comment by rrabherufigma** [comment]
Hi @bbshih , please can you confirm which OS and which node version you are using?

**Comment by bbshih** [comment]
mac OS 14.5 - node v18.13.0

**Comment by tomduncalf-figma** [comment]
Hey @bbshih, sorry to hear you're having issues! We've not seen this one before so might need to do some debugging to get to the bottom of it.

How did you install Code Connect?

If you run `npm list -a | grep minimatch`, do you get any output?

Thanks

**Comment by bbshih** [comment]
I installed via `yarn add @figma/code-connect`

Here's the output:
```
│ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob
│ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect
npm ERR! code ELSPROBLEMS
npm ERR! extraneous: @gar/promisify@1.1.3 /Users/billy.shih/dev/hui/node_modules/@gar/promisify
npm ERR! extraneous: @npmcli/fs@2.1.2 /Users/billy.shih/dev/hui/node_modules/@npmcli/fs
npm ERR! extraneous: @npmcli/move-file@2.0.1 /Users/billy.shih/dev/hui/node_modules/@npmcli/move-file
npm ERR! extraneous: @tootallnate/once@2.0.0 /Users/billy.shih/dev/hui/node_modules/@tootallnate/once
npm ERR! extraneous: abbrev@1.1.1 /Users/billy.shih/dev/hui/node_modules/abbrev
npm ERR! extraneous: agentkeepalive@4.2.1 /Users/billy.shih/dev/hui/node_modules/agentkeepalive
npm ERR! extraneous: aproba@1.2.0 /Users/billy.shih/dev/hui/node_modules/aproba
npm ERR! extraneous: are-we-there-yet@3.0.1 /Users/billy.shih/dev/hui/node_modules/are-we-there-yet
npm ERR! extraneous: cacache@16.1.3 /Users/billy.shih/dev/hui/node_modules/cacache
npm ERR! extraneous: color-support@1.1.3 /Users/billy.shih/dev/hui/node_modules/color-support
npm ERR! extraneous: console-control-strings@1.1.0 /Users/billy.shih/dev/hui/node_modules/console-control-strings
npm ERR! invalid: cypress@13.6.6 /Users/billy.shih/dev/hui/node_modules/cypress
npm ERR! extraneous: delegates@1.0.0 /Users/billy.shih/dev/hui/node_modules/delegates
npm ERR! extraneous: err-code@2.0.3 /Users/billy.shih/dev/hui/node_modules/err-code
npm ERR! extraneous: gauge@4.0.4 /Users/billy.shih/dev/hui/node_modules/gauge
npm ERR! extraneous: has-unicode@2.0.1 /Users/billy.shih/dev/hui/node_modules/has-unicode
npm ERR! extraneous: http-cache-semantics@4.1.1 /Users/billy.shih/dev/hui/node_modules/http-cache-semantics
npm ERR! extraneous: humanize-ms@1.2.1 /Users/billy.shih/dev/hui/node_modules/humanize-ms
npm ERR! extraneous: infer-owner@1.0.4 /Users/billy.shih/dev/hui/node_modules/infer-owner
npm ERR! extraneous: is-lambda@1.0.1 /Users/billy.shih/dev/hui/node_modules/is-lambda
npm ERR! extraneous: make-fetch-happen@10.2.1 /Users/billy.shih/dev/hui/node_modules/make-fetch-happen
npm ERR! invalid: minimatch@3.0.8 /Users/billy.shih/dev/hui/node_modules/minimatch
npm ERR! extraneous: minipass-collect@1.0.2 /Users/billy.shih/dev/hui/node_modules/minipass-collect
npm ERR! extraneous: minipass-fetch@2.1.2 /Users/billy.shih/dev/hui/node_modules/minipass-fetch
npm ERR! extraneous: minipass-flush@1.0.5 /Users/billy.shih/dev/hui/node_modules/minipass-flush
npm ERR! extraneous: minipass-pipeline@1.2.4 /Users/billy.shih/dev/hui/node_modules/minipass-pipeline
npm ERR! extraneous: minipass-sized@1.0.3 /Users/billy.shih/dev/hui/node_modules/minipass-sized
npm ERR! extraneous: node-gyp@9.3.0 /Users/billy.shih/dev/hui/node_modules/node-gyp
npm ERR! extraneous: nopt@6.0.0 /Users/billy.shih/dev/hui/node_modules/nopt
npm ERR! extraneous: npmlog@6.0.2 /Users/billy.shih/dev/hui/node_modules/npmlog
npm ERR! extraneous: promise-inflight@1.0.1 /Users/billy.shih/dev/hui/node_modules/promise-inflight
npm ERR! extraneous: promise-retry@2.0.1 /Users/billy.shih/dev/hui/node_modules/promise-retry
npm ERR! extraneous: retry@0.12.0 /Users/billy.shih/dev/hui/node_modules/retry
npm ERR! extraneous: socks@2.7.1 /Users/billy.shih/dev/hui/node_modules/socks
npm ERR! extraneous: ssri@9.0.1 /Users/billy.shih/dev/hui/node_modules/ssri
npm ERR! extraneous: unique-filename@2.0.1 /Users/billy.shih/dev/hui/node_modules/unique-filename
npm ERR! extraneous: unique-slug@3.0.0 /Users/billy.shih/dev/hui/node_modules/unique-slug
npm ERR! extraneous: wide-align@1.1.5 /Users/billy.shih/dev/hui/node_modules/wide-align
npm ERR! extraneous: mkdirp@1.0.4 /Users/billy.shih/dev/hui/node_modules/@npmcli/move-file/node_modules/mkdirp
npm ERR! missing: jest@*, required by @storybook/addon-storyshots@7.6.17
npm ERR! extraneous: depd@1.1.2 /Users/billy.shih/dev/hui/node_modules/agentkeepalive/node_modules/depd
npm ERR! extraneous: glob@8.0.3 /Users/billy.shih/dev/hui/node_modules/cacache/node_modules/glob
npm ERR! extraneous: lru-cache@7.14.1 /Users/billy.shih/dev/hui/node_modules/cacache/node_modules/lru-cache
npm ERR! extraneous: mkdirp@1.0.4 /Users/billy.shih/dev/hui/node_modules/cacache/node_modules/mkdirp
npm ERR! invalid: minimist@1.2.7 /Users/billy.shih/dev/hui/node_modules/minimist
npm ERR! extraneous: agent-base@6.0.2 /Users/billy.shih/dev/hui/node_modules/make-fetch-happen/node_modules/agent-base
npm ERR! extraneous: http-proxy-agent@5.0.0 /Users/billy.shih/dev/hui/node_modules/make-fetch-happen/node_modules/http-proxy-agent
npm ERR! extraneous: lru-cache@7.14.1 /Users/billy.shih/dev/hui/node_modules/make-fetch-happen/node_modules/lru-cache
npm ERR! extraneous: socks-proxy-agent@7.0.0 /Users/billy.shih/dev/hui/node_modules/make-fetch-happen/node_modules/socks-proxy-agent
npm ERR! missing: jest@>= 29.0.0, required by jest-specific-snapshot@8.0.0
npm ERR! missing: preact@>=10, required by preact-render-to-string@5.2.0
npm ERR! invalid: react@17.0.1 /Users/billy.shih/dev/hui/node_modules/react
npm ERR! invalid: axe-core@4.4.2 /Users/billy.shih/dev/hui/node_modules/axe-core
npm ERR! invalid: typescript@4.9.3 /Users/billy.shih/dev/hui/node_modules/typescript
npm ERR! invalid: webpack@5.88.2 /Users/billy.shih/dev/hui/node_modules/webpack
npm ERR! invalid: terser@5.14.2 /Users/billy.shih/dev/hui/node_modules/terser
npm ERR! extraneous: @babel/types@7.23.9 /Users/billy.shih/dev/hui/node_modules/@svgr/core/node_modules/@babel/parser/node_modules/@babel/types
npm ERR! invalid: nth-check@2.0.1 /Users/billy.shih/dev/hui/node_modules/nth-check
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck
│ │ │ ├── @types/minimatch@3.0.5
│ │ │ └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob
│ │ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob
│ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob
│ │ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/builder-webpack5/node_modules/glob
│ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob
│ │ │ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/builder-webpack5/node_modules/glob, "^9.0.1" from node_modules/@storybook/preset-react-webpack/node_modules/glob
│ │ │ │ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/builder-webpack5/node_modules/glob, "^9.0.1" from node_modules/@storybook/preset-react-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/react-webpack5/node_modules/glob
│   └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob
│ │ │ └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob
│ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import
│ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob
│ │ └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob
│ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import
├─┬ minimatch@3.0.8 invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import
│ │ ├── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob
│ │ └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/billy.shih/.npm/_logs/2024-06-03T23_10_58_646Z-debug-0.log
│   │ │ │   │ └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/builder-webpack5/node_modules/glob, "^9.0.1" from node_modules/@storybook/preset-react-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/react-webpack5/node_modules/glob, "^3.1.2" from node_modules/jake, "^5.0.1" from node_modules/filelist
│   │ │ │   └── minimatch@3.0.8 deduped invalid: "^9.0.4" from the root project, "^9.0.3" from node_modules/@figma/code-connect, "^3.1.2" from node_modules/eslint-plugin-import, "5.0.1" from node_modules/mocha, "^9.0.4" from node_modules/@figma/code-connect/node_modules/glob, "^7.4.6" from node_modules/depcheck, "^5.0.1" from node_modules/@rollup/plugin-commonjs/node_modules/glob, "^9.0.1" from node_modules/@storybook/addon-storyshots/node_modules/glob, "^5.0.1" from node_modules/babel-plugin-module-resolver/node_modules/glob, "^5.0.1" from node_modules/cacache/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-common/node_modules/glob, "^9.0.1" from node_modules/@storybook/core-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/builder-webpack5/node_modules/glob, "^9.0.1" from node_modules/@storybook/preset-react-webpack/node_modules/glob, "^9.0.1" from node_modules/@storybook/react-webpack5/node_modules/glob, "^3.1.2" from node_modules/jake
```

**Comment by bbshih** [comment]
Ah I figured it out. We had a minimatch resolution that was forcing a certain version. Removing that fixed it.
